/**
 * @fileoverview Build detail page - displays single or team builds
 * @module app/b/[id]/page
 *
 * Statically rendered / ISR-cached Server Component that fetches and displays
 * a complete build. Handles both single-character and team (8-hero) builds.
 * View tracking and per-user state are handled client-side (see ./client).
 *
 * Route: /b/[id] where id is a 7-character nanoid
 *
 * @see lib/services/builds.ts for data fetching
 * @see components/build/ for UI components
 */
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { getBuildById } from '@/lib/services/builds'
import { getSkillsByIds, type Skill } from '@/lib/gw/skills'
import { PROFESSION_COLORS, SITE_URL } from '@/lib/constants'
import { BuildPageClient } from './client'
import type { SkillBar } from '@/types/database'

// ISR: build pages are public content and rendered from cache so crawler +
// user traffic doesn't invoke a function per request. Per-user state (owner,
// stars, views) is resolved client-side. Edits trigger on-demand revalidation.
export const revalidate = 300
export const dynamicParams = true

// Opt into ISR for the dynamic [id] segment. Returning [] prerenders nothing
// at build time; each build id renders and is cached on first request, then
// served from cache (no function invocation) until revalidated.
export function generateStaticParams() {
  return []
}

interface BuildPageProps {
  params: Promise<{ id: string }>
}

/**
 * Generates dynamic metadata for build pages
 *
 * Called by Next.js at request time to populate <head> tags.
 * Fetches build data (cached/deduped with page fetch).
 *
 * OG images are dynamically generated by opengraph-image.tsx
 */
export async function generateMetadata({
  params,
}: BuildPageProps): Promise<Metadata> {
  const { id } = await params
  const build = await getBuildById(id)

  // Only published builds are publicly viewable; everything else is "not found".
  if (!build || build.moderation_status !== 'published') {
    return {
      title: 'Build not found',
    }
  }

  // Build description based on build type
  const totalPlayers = build.bars.reduce(
    (sum, bar) => sum + (bar.playerCount || 1),
    0
  )
  const isSingleBuild = build.bars.length === 1 && totalPlayers === 1
  const professionPart = isSingleBuild
    ? `${build.bars[0].primary}${build.bars[0].secondary !== 'None' ? `/${build.bars[0].secondary}` : ''}`
    : build.bars
        .slice(0, 3)
        .map(bar => bar.primary)
        .join(', ') +
      (build.bars.length > 3 ? ` +${build.bars.length - 3}` : '')

  const description = isSingleBuild
    ? `${professionPart} build`
    : `${totalPlayers}-player team: ${professionPart}`

  // Bump version to invalidate CDN cache when OG image design changes
  const ogImageUrl = `${SITE_URL}/api/og/${build.id}?v=3`
  const pageUrl = `${SITE_URL}/b/${build.id}`

  return {
    title: build.name,
    description,
    // Private (link-only) builds are accessible by URL but must not be indexed.
    robots: build.is_private
      ? { index: false, follow: false }
      : undefined,
    openGraph: {
      title: build.name,
      description,
      type: 'article',
      url: pageUrl,
      siteName: 'GW1 Builds',
      images: [{ url: ogImageUrl, width: 1200, height: 630 }],
    },
    twitter: {
      card: 'summary_large_image',
      title: build.name,
      description,
      images: [ogImageUrl],
    },
  }
}

/**
 * Collects all skill IDs from build bars (including variants) and fetches skill data
 */
async function getSkillsForBuild(
  bars: SkillBar[]
): Promise<Map<number, Skill>> {
  // Collect all unique skill IDs from base bars and variants
  const skillIds = new Set<number>()
  for (const bar of bars) {
    // Base bar skills
    for (const id of bar.skills) {
      if (id > 0) skillIds.add(id)
    }
    // Variant skills
    if (bar.variants) {
      for (const variant of bar.variants) {
        for (const id of variant.skills) {
          if (id > 0) skillIds.add(id)
        }
      }
    }
  }

  // Convert to array once (not on every iteration)
  const skillIdsArray = Array.from(skillIds)

  // Fetch all skills
  const skills = await getSkillsByIds(skillIdsArray)
  const skillMap = new Map<number, Skill>()

  skillIdsArray.forEach((id, index) => {
    const skill = skills[index]
    if (skill) {
      skillMap.set(id, skill)
    }
  })

  return skillMap
}

/**
 * Build detail page component
 *
 * Statically rendered / ISR-cached Server Component that:
 * 1. Fetches public build data by ID (cookieless)
 * 2. Shows 404 for missing or non-published builds
 * 3. Fetches skill data (icons served locally from /public/skills/)
 * 4. Renders the appropriate view (single vs team)
 *
 * Per-user concerns (ownership, edit button, star state, view tracking) are
 * resolved client-side in BuildPageClient so this page stays cacheable.
 */
export default async function BuildPage({ params }: BuildPageProps) {
  const { id } = await params

  const build = await getBuildById(id)

  // Only published builds are publicly viewable. Delisted/appealed builds 404
  // here; owners manage them via the authenticated editor (/b/[id]/edit).
  // Private (is_private) builds stay published and remain link-accessible.
  if (!build || build.moderation_status !== 'published') {
    notFound()
  }

  const skillMap = await getSkillsForBuild(build.bars as SkillBar[])

  return (
    <BuildPageClient
      build={build}
      skillMap={Object.fromEntries(skillMap)}
      professionColors={PROFESSION_COLORS}
      starCount={build.star_count}
    />
  )
}
